-- SQL Injection Simulator Seed Data
-- Educational cybersecurity project - for learning purposes only
-- This file populates the database with test data for simulation

-- Clear existing data (for development/testing)
DELETE FROM Alerts;
DELETE FROM LoginAttempts;
DELETE FROM Users;

-- Reset identity columns
DBCC CHECKIDENT ('Users', RESEED, 0);
DBCC CHECKIDENT ('LoginAttempts', RESEED, 0);
DBCC CHECKIDENT ('Alerts', RESEED, 0);

-- Insert test users with BCrypt-style password hashes
-- Note: In a real implementation, these would be generated by the UserManager class
INSERT INTO Users (Username, PasswordHash, CreatedDate, IsActive) VALUES
('admin', '$2a$10$N9qo8uLOickgx2ZMRZoMye.Uo5HLBnJ2N0TZ/3k1a2b3c4d5e6f7g8', DATEADD(day, -30, GETDATE()), 1),
('user1', '$2a$10$N9qo8uLOickgx2ZMRZoMye.Uo5HLBnJ2N0TZ/3k1a2b3c4d5e6f7g9', DATEADD(day, -25, GETDATE()), 1),
('guest', '$2a$10$N9qo8uLOickgx2ZMRZoMye.Uo5HLBnJ2N0TZ/3k1a2b3c4d5e6f7ga', DATEADD(day, -20, GETDATE()), 1),
('testuser', '$2a$10$N9qo8uLOickgx2ZMRZoMye.Uo5HLBnJ2N0TZ/3k1a2b3c4d5e6f7gb', DATEADD(day, -15, GETDATE()), 1),
('developer', '$2a$10$N9qo8uLOickgx2ZMRZoMye.Uo5HLBnJ2N0TZ/3k1a2b3c4d5e6f7gc', DATEADD(day, -10, GETDATE()), 1),
('inactive_user', '$2a$10$N9qo8uLOickgx2ZMRZoMye.Uo5HLBnJ2N0TZ/3k1a2b3c4d5e6f7gd', DATEADD(day, -5, GETDATE()), 0);

-- Insert sample legitimate login attempts (historical data for analysis)
INSERT INTO LoginAttempts (Username, InputPayload, PasswordInput, AttemptTime, IsSuccessful, IsInjection, IpAddress, UserAgent, ResponseTime, QueryExecuted) VALUES
-- Successful logins
('admin', 'admin', 'correct_password', DATEADD(hour, -24, GETDATE()), 1, 0, '192.168.1.100', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)', 45, 'SELECT * FROM Users WHERE Username = @username AND PasswordHash = @password'),
('user1', 'user1', 'correct_password', DATEADD(hour, -23, GETDATE()), 1, 0, '192.168.1.101', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)', 42, 'SELECT * FROM Users WHERE Username = @username AND PasswordHash = @password'),
('guest', 'guest', 'correct_password', DATEADD(hour, -22, GETDATE()), 1, 0, '192.168.1.102', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)', 38, 'SELECT * FROM Users WHERE Username = @username AND PasswordHash = @password'),

-- Failed legitimate attempts
('admin', 'admin', 'wrong_password', DATEADD(hour, -21, GETDATE()), 0, 0, '192.168.1.100', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)', 43, 'SELECT * FROM Users WHERE Username = @username AND PasswordHash = @password'),
('user1', 'user1', 'invalid_pass', DATEADD(hour, -20, GETDATE()), 0, 0, '192.168.1.101', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)', 41, 'SELECT * FROM Users WHERE Username = @username AND PasswordHash = @password'),
('nonexistent', 'nonexistent', 'any_password', DATEADD(hour, -19, GETDATE()), 0, 0, '192.168.1.103', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)', 39, 'SELECT * FROM Users WHERE Username = @username AND PasswordHash = @password');

-- Insert sample SQL injection attempts (educational examples)
INSERT INTO LoginAttempts (Username, InputPayload, PasswordInput, AttemptTime, IsSuccessful, IsInjection, IpAddress, UserAgent, ResponseTime, QueryExecuted) VALUES
-- Classic injection attempts
('admin'' OR ''1''=''1', 'admin'' OR ''1''=''1', 'anything', DATEADD(hour, -18, GETDATE()), 0, 1, '10.0.0.50', 'curl/7.68.0', 125, 'SELECT * FROM Users WHERE Username = ''admin'' OR ''1''=''1'' AND PasswordHash = ''anything'''),
('admin''--', 'admin''--', 'ignored', DATEADD(hour, -17, GETDATE()), 0, 1, '10.0.0.51', 'python-requests/2.25.1', 134, 'SELECT * FROM Users WHERE Username = ''admin''--'' AND PasswordHash = ''ignored'''),
('admin', ''' OR 1=1--', DATEADD(hour, -16, GETDATE()), 0, 1, '10.0.0.52', 'Postman/8.0.0', 98, 'SELECT * FROM Users WHERE Username = ''admin'' AND PasswordHash = ''' OR 1=1--'''),

-- Union-based injection attempts
('admin'' UNION SELECT NULL,''hacker'',''fakehash''--', 'admin'' UNION SELECT NULL,''hacker'',''fakehash''--', 'password', DATEADD(hour, -15, GETDATE()), 0, 1, '10.0.0.53', 'sqlmap/1.5.2', 187, 'SELECT * FROM Users WHERE Username = ''admin'' UNION SELECT NULL,''hacker'',''fakehash''--'' AND PasswordHash = ''password'''),
('test', ''' UNION ALL SELECT username, password FROM users--', DATEADD(hour, -14, GETDATE()), 0, 1, '10.0.0.54', 'Manual Testing', 156, 'SELECT * FROM Users WHERE Username = ''test'' AND PasswordHash = ''' UNION ALL SELECT username, password FROM users--'''),

-- Time-based injection attempts
('admin', '; WAITFOR DELAY ''00:00:05''--', DATEADD(hour, -13, GETDATE()), 0, 1, '10.0.0.55', 'Custom Script', 5234, 'SELECT * FROM Users WHERE Username = ''admin'' AND PasswordHash = ''; WAITFOR DELAY ''00:00:05''--'''),

-- Error-based injection attempts
('admin''', 'admin''', 'convert(int,@@version)', DATEADD(hour, -12, GETDATE()), 0, 1, '10.0.0.56', 'Burp Suite', 67, 'SELECT * FROM Users WHERE Username = ''admin''''' AND PasswordHash = ''convert(int,@@version)'''),

-- Boolean-based blind injection
('admin'' AND ''1''=''1', 'admin'' AND ''1''=''1', 'password', DATEADD(hour, -11, GETDATE()), 0, 1, '10.0.0.57', 'Custom Tool', 89, 'SELECT * FROM Users WHERE Username = ''admin'' AND ''1''=''1'' AND PasswordHash = ''password'''),
('admin'' AND ''1''=''2', 'admin'' AND ''1''=''2', 'password', DATEADD(hour, -10, GETDATE()), 0, 1, '10.0.0.57', 'Custom Tool', 91, 'SELECT * FROM Users WHERE Username = ''admin'' AND ''1''=''2'' AND PasswordHash = ''password'''),

-- Advanced payload attempts
('admin', '''; DROP TABLE Users; --', DATEADD(hour, -9, GETDATE()), 0, 1, '10.0.0.58', 'Malicious Script', 78, 'SELECT * FROM Users WHERE Username = ''admin'' AND PasswordHash = ''''; DROP TABLE Users; --'''),
('test', ''' OR (SELECT COUNT(*) FROM Users) > 0--', DATEADD(hour, -8, GETDATE()), 0, 1, '10.0.0.59', 'Automated Tool', 112, 'SELECT * FROM Users WHERE Username = ''test'' AND PasswordHash = ''' OR (SELECT COUNT(*) FROM Users) > 0--''');

-- Insert sample security alerts
INSERT INTO Alerts (Username, AlertType, Severity, Details, TriggerCondition, AlertTime) VALUES
('admin'' OR ''1''=''1', 'SQL_INJECTION', 'HIGH', 'Classic OR-based SQL injection pattern detected', 'Input contains OR clause with always-true condition', DATEADD(hour, -18, GETDATE())),
('admin''--', 'SQL_INJECTION', 'HIGH', 'SQL comment marker detected in username field', 'Input contains SQL comment sequence', DATEADD(hour, -17, GETDATE())),
('admin', 'SQL_INJECTION', 'CRITICAL', 'Destructive SQL command detected', 'Password field contains DROP TABLE statement', DATEADD(hour, -9, GETDATE())),
('admin', 'BRUTE_FORCE', 'MEDIUM', 'Multiple failed login attempts detected', '3 failed attempts within 1 hour', DATEADD(hour, -16, GETDATE())),
('10.0.0.50-59', 'SUSPICIOUS_ACTIVITY', 'HIGH', 'Multiple injection attempts from IP range', '10+ injection attempts from similar IP addresses', DATEADD(hour, -12, GETDATE()));

-- Update some users with realistic failed login counts
UPDATE Users SET FailedLoginCount = 2 WHERE Username = 'admin';
UPDATE Users SET FailedLoginCount = 1 WHERE Username = 'user1';
UPDATE Users SET LastLoginDate = DATEADD(hour, -24, GETDATE()) WHERE Username = 'admin';
UPDATE Users SET LastLoginDate = DATEADD(hour, -23, GETDATE()) WHERE Username = 'user1';
UPDATE Users SET LastLoginDate = DATEADD(hour, -22, GETDATE()) WHERE Username = 'guest';

PRINT 'Seed data inserted successfully:';
PRINT '- ' + CAST((SELECT COUNT(*) FROM Users) AS VARCHAR(10)) + ' test users created';
PRINT '- ' + CAST((SELECT COUNT(*) FROM LoginAttempts) AS VARCHAR(10)) + ' login attempts logged';
PRINT '- ' + CAST((SELECT COUNT(*) FROM LoginAttempts WHERE IsInjection = 1) AS VARCHAR(10)) + ' injection attempts identified';
PRINT '- ' + CAST((SELECT COUNT(*) FROM Alerts) AS VARCHAR(10)) + ' security alerts generated';
PRINT '';
PRINT 'Test User Accounts (password hashes are BCrypt format):';
PRINT '- admin (active, 2 failed attempts)';
PRINT '- user1 (active, 1 failed attempt)';
PRINT '- guest (active, no failed attempts)';
PRINT '- testuser (active, no failed attempts)';
PRINT '- developer (active, no failed attempts)';
PRINT '- inactive_user (inactive account)';
PRINT '';
PRINT 'Database ready for SQL Injection Simulator!';